apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: model-service
  template:
    metadata:
      labels:
        app: model-service
    spec:
      containers:
      - name: model-service
        image: model-service:latest
        ports:
        - containerPort: 5000
      - name: data-processor
        image: data-processor:latest
        env:
        - name: CONFIG_FILE
          value: /config/processing.yaml
